@protocol = http
@hostname = localhost
@port = 3000
@host = {{hostname}}:{{port}}
@url = http://node-server.online/r/assets/week.txt
# @url = test

###
# @name root
GET {{protocol}}://{{host}}/
###
# @name login
GET {{protocol}}://{{host}}/login/
###
# @name code
GET {{protocol}}://{{host}}/code/
###
# @name sha1-hola
GET {{protocol}}://{{host}}/sha1/hola/
###
# @name sha1-mundo
GET {{protocol}}://{{host}}/sha1/mundo/
###
# @name req-path
GET {{protocol}}://{{host}}/req/{{url}}
###
# @name req-query
GET {{protocol}}://{{host}}/req/?addr={{url}}
###
# @name req-post
POST {{protocol}}://{{host}}/req/
Content-Type: application/x-www-form-urlencoded

addr={{url}}
