@protocol = http
@hostname = localhost
@port = 3000
# @protocol = https
# @hostname = hessian-openedu-nodejs-week6.herokuapp.com
# @port = 443
@host = {{hostname}}:{{port}}
@url = http://node-server.online/r/assets/week.txt
# @url = test

###
# @name root
GET {{protocol}}://{{host}}/
###
# @name login
GET {{protocol}}://{{host}}/login/
###
# @name code
GET {{protocol}}://{{host}}/code/
###
# @name sha1-hola
GET {{protocol}}://{{host}}/sha1/hola/
###
# @name sha1-mundo
GET {{protocol}}://{{host}}/sha1/mundo/
###
# @name req-query
GET {{protocol}}://{{host}}/req/?addr={{url}}
###
# @name req-post
POST {{protocol}}://{{host}}/req/
Content-Type: application/x-www-form-urlencoded

&addr={{url}}
###
# @name insert-get
GET {{protocol}}://{{host}}/insert/
###
# @name insert-post
POST {{protocol}}://{{host}}/insert/
Content-Type: application/x-www-form-urlencoded

&login=frodo
&password=ring
&URL=mongodb%2Bsrv://writer:CxqPNT7CjY6EEGw@cluster0.mrnaa.mongodb.net/test?retryWrites=true%26w=majority
