@protocol = http
@hostname = localhost
# @port = 3000
@port = 80
# @protocol = https
# @hostname = hessian-openedu-nodejs-week6.herokuapp.com
# @port = 443
@host = {{hostname}}:{{port}}
@requrl = http://node-server.online/r/assets/week.txt
# @requrl = test
@renderurl = http://kodaktor.ru/j/unsafe_0ebdb
@testurl = https://kodaktor.ru/g/80b5cdf

###
# @name root
GET {{protocol}}://{{host}}/
###
# @name login
GET {{protocol}}://{{host}}/login/
###
# @name code
GET {{protocol}}://{{host}}/code/
###
# @name sha1-hola
GET {{protocol}}://{{host}}/sha1/hola/
###
# @name sha1-mundo
GET {{protocol}}://{{host}}/sha1/mundo/
###
# @name req-query
GET {{protocol}}://{{host}}/req/?addr={{requrl}}
###
# @name req-post
POST {{protocol}}://{{host}}/req/
Content-Type: application/x-www-form-urlencoded

&addr={{requrl}}
###
# @name insert-get
GET {{protocol}}://{{host}}/insert/
###
# @name insert-post
POST {{protocol}}://{{host}}/insert/
Content-Type: application/x-www-form-urlencoded

&login=frodo
&password=ring
&URL=mongodb%2Bsrv://writer:CxqPNT7CjY6EEGw@cluster0.mrnaa.mongodb.net/test?retryWrites=true%26w=majority
###
# @name wordpress
GET {{protocol}}://{{host}}/wordpress/wp-json/wp/v2/posts/1
###
# @name render-get
GET {{protocol}}://{{host}}/render/?addr={{renderurl}}
###
# @name render-post
POST {{protocol}}://{{host}}/render/?addr={{renderurl}}
Content-Type: application/json

{
    "random2": "0.4433",
    "random3": "0.1199"
}
###
# @name test-puppet
GET {{protocol}}://{{host}}/test/?URL={{testurl}}
